### ISSUE TITLE
License request

### ISSUE THREAD

**Issue by corliss** [kashifimran/math-editor#1]
Hello - your code is very interesting. However the GPL license is very restrictive, particularly for mobile devices. Could you possibly release it under a non-copyleft license such as MIT or BSD?
Much appreciated.

**Comment by kashifimran** [comment]
Hi,
For now, public release license is not going to change for certain reasons. 

However, I do allow more freedom to users on case-to-case basis. If you are creating a useful product, tell me about it trough email and I will grant you commercial license at no charge. 
Kashif

**Comment by ProjectInitiative** [comment]
Hello, I would also like to request a license and ask a few questions. Where might I find your email address?

**Comment by kashifimran** [comment]
Please contact using the contact form on http://mathiversity.com/
