### ISSUE TITLE
License on CodeProject article is GPLv3 ? and in this repo is MIT

### ISSUE THREAD

**Issue by prepare** [kashifimran/math-editor#2]
@kashifimran,

I checked your CodeProject's article (year 2015). 
It still uses GPLv3.

but in this repo, (newer, 2016) it is MIT.

---

Could you change/ update the license on the CodeProject too?

Thank you 

:)

**Comment by kashifimran** [comment]
Updated, sir.

**Comment by prepare** [comment]
Hello! @kashifimran ,

I'm one of the developers of the Typography(https://github.com/LayoutFarm/Typography).

I respect your library.

Would you mind if I integrate some of you code (about Math Layout core) 
into the Typography lib, (_Implement math table_ : https://github.com/LayoutFarm/Typography/issues/20).

**Comment by kashifimran** [comment]
Hi @prepare,
Feel free to use the code.

**Comment by prepare** [comment]
Thank you very much

:)
