### ISSUE TITLE
Export and Integration

### ISSUE THREAD

**Issue by CoryGH** [kashifimran/math-editor#3]
This isn't really an issue/bug but more a list of feature requests, if you're still working on this.

- More standard XML serialization via IXmlSerializable would make the system easier to work with by providing cleaner and more concise XML output.
- Being able to export to a format or plug directly into a library like [http://mathparser.org/](http://mathparser.org/) would be really useful in terms of using this as more than a control in c#.

If this is still active I'd be willing to help a bit on these, just curious if I should be collaborating or making a fork.

**Comment by kashifimran** [comment]
@CoryGH. Thanks for sharing your thoughts. This project is not active anymore, as everyone is now moving to bring such tools to the web/browser based solutions. This repository has only an educational value now.

**Comment by CoryGH** [comment]
@kashifimran Thanks, I find it useful personally - I like MathQuill on the browser but need to stick an equation editor + parser into a c# application on the desktop and this one looks the most well developed for the editor side.
